services:
  spark:
    image: dev-spark:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-spark-container
    user: root
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - ./:/workspace
    env_file:
      - .env
    entrypoint: /bin/bash -c "/workspace/config_databricks.sh && /workspace/config_git.sh && exec /bin/bash"