services:
  spark:
    image: vida-spark:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - vida-spark:latest
    container_name: vida-spark-container
    user: root
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - ./:/workspace